import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProfileCard from "../components/profileCard";
import NavBar from "../components/navBar";
import Container from "../components/container";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-neutral-950 subtle-grid-background flex flex-col items-center py-6 px-4`}
      >
        <div className="flex flex-col lg:flex-row gap-8 w-full max-w-6xl mt-4">
          <aside className="w-full lg:w-80 lg:sticky lg:top-8 h-fit">
            <ProfileCard />
          </aside>
          <section className="flex-1 flex flex-col gap-8">
            <Container className="dot-grid-background relative">
              {/* Position navbar responsively */}
              <div className="absolute top-4 right-4 z-10">
                <NavBar />
              </div>
              {children}
            </Container>
          </section>
        </div>
      </body>
    </html>
  );
}
